### ISSUE TITLE
no encryption

### ISSUE THREAD

**Issue by Co1t0n** [CosmicProxy-DEV/Cosmic#4]
dude yall gotto add encryption . a normal link(https://qdtjde-8080.csb.app/service/https://reddit.com) would be blocked on the majority of chromebooks. other unblocker linnks look somethings likeexample.com/fjwuoribgowribgoiwbfowibfr484oh834b
or smth link that.
my blocking service filters out the keywords and blocks it

**Comment by Tacogamerman** [comment]
Bet
